### ISSUE TITLE
Fix Repository Name Must Be Lowercase Error in Docker Tagging

### ISSUE THREAD

**Issue by fred-maussion** [fred-maussion/elastic-enabled-bank#13]
## **Issue Description**
While attempting to push a Docker image to **GitHub Container Registry (GHCR)**, the following error occurs:

```
ERROR: invalid tag "ghcr.io/TimBrophy/elastic-enabled-bank:latest": repository name must be lowercase
```

This happens because **GitHub repository owner names may contain uppercase letters**, but GHCR **requires repository names to be lowercase**.

## **Proposed Fix**
To ensure that the repository owner is always in lowercase when setting the Docker image name, we will update the GitHub Actions workflow by adding a step to **convert `github.repository_owner` to lowercase**.

#### **Before (Problematic Code)**
```yaml
- name: Build and Tag Docker Image
  run: |
    IMAGE_PATH=ghcr.io/${{ github.repository_owner }}/elastic-enabled-bank
    docker build -t $IMAGE_PATH:latest .
    docker push $IMAGE_PATH:latest
```

#### **After (Fixed Code)**
```yaml
- name: Set Lowercase Owner Name
  run: |
    echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
  env:
    OWNER: '${{ github.repository_owner }}'

- name: Build and Tag Docker Image
  run: |
    IMAGE_PATH=ghcr.io/${OWNER_LC}/elastic-enabled-bank
    docker build -t $IMAGE_PATH:latest .
    docker push $IMAGE_PATH:latest
```

## **Why This Fix Works**
- The first step **converts `github.repository_owner` to lowercase** and stores it in the **GitHub Actions environment (`GITHUB_ENV`)**.
- The Docker image tag then uses the lowercase value, ensuring it meets GHCR’s **lowercase repository name requirement**.

## **Steps to Implement**
1. **Update the GitHub Actions workflow file** to include the new step.
2. **Re-run the workflow** to verify that the error no longer occurs.

---
### **References**
- [GitHub Actions Documentation](https://docs.github.com/en/actions/learn-github-actions/environment-variables)
- [GHCR Repository Naming Requirements](https://docs.github.com/en/packages/working-with-a-github-packages-registry)
